trigger:
  - none
jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        clean: all

      - task: NodeTool@0
        displayName: Use Node 14.x
        inputs:
          versionSpec: 14.x
          latest: true

      - task: npmAuthenticate@0
        inputs:
          workingFile: .npmrc

      - script: npm install
        displayName: npm install

      - script: npm audit
        displayName: npm audit

      - script: npm run build
        displayName: npm build

      - script: npm run build:package
        displayName: npm build package
