trigger:
- main

pr: 
- main

name: $(date:yyyy.MM.dd)$(Rev:.r)

resources:
  repositories:
    - repository: build-pipeline-scripts
      type: git
      name: iModelTechnologies/imodeljs-build-pipeline-scripts

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: ci.yaml

  - stage: PublishNpmjs
    displayName: Publish to Npmjs
    dependsOn: Build
    variables:
      version: $[ stageDependencies.Build.Build.outputs['checkPublish.version'] ]

    jobs:
      - template: templates/npmjs-publish-deployment.yaml@build-pipeline-scripts
        parameters:
          path: itwin-synchronization-report-react-$(version).tgz
          artifactName: tarball
