/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/
import { WorkflowMapping } from './report-data-typings';

export const defaultWorkflowMapping: WorkflowMapping = {
  Authorization: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Briefcase To iModel': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  BusinessProperties: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  Compatibility: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Corrupt Data': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Digital Rights': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  DiskIO: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  Filtering: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  IModel: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Inconsistent Data': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  InputFiles: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Missing Data': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  Synchronization: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  ToolkitError: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  UnexpectedData: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  Unknown: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  Unsupported: {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
  'Visual Fidelity': {
    Attachment: ['Design Review'],
    Alert: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    'BRep-Surface': ['Design Review'],
    Briefcase: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigXMLFile: ['Design Review'],
    Config: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ConfigVariable: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DefinitionFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Document: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DataSource: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    DuplicateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECInstance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECRelationshipClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECProperty: ['Design Review', 'Reporting', 'Construction'],
    ECCustomAttribute: ['Design Review', 'Reporting', 'Construction'],
    Element: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECSQL: ['Design Review', 'Reporting', 'Construction'],
    ECDB: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    EmbeddedFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileHandler: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Font: ['Design Review'],
    FileNotFound: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    FileStatus: ['Design Review'],
    GeometryElement: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GroupElements: ['Design Review'],
    Geometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportGroup: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvisibleElement: ['Design Review'],
    Instance: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InconsistentTransformsForEmbeddedReference: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    iModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportXData: ['Design Review'],
    JobDefinitionModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    LineStyle: ['Design Review'],
    Level: ['Design Review'],
    Link: ['Design Review'],
    LargeBRep: ['Design Review'],
    Material: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingSoftwareDependency: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Model: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    NonSupportedImageFile: ['Design Review'],
    NamedGroup: ['Design Review'],
    NotADgnDb: ['Design Review'],
    PointCloudConversionError: ['Design Review'],
    PointCloudFile: ['Design Review'],
    ProjectExtentsAdjusted: ['Design Review'],
    Raster: ['Design Review'],
    Range: ['Design Review'],
    RealityModelTileSets: ['Design Review'],
    RootModel: ['Design Review'],
    ReferenceFile: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    References: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    RepositoryLink: ['Design Review'],
    SupplementalECSchema: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Sheet: ['Design Review'],
    SyncInfo: ['Design Review'],
    ThreeMx: ['Design Review'],
    Undefined: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Units: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    View: ['Design Review'],
    MissingGeometry: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    InvalidInputData: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGroupMember: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MaterialNoFile: ['Design Review', 'Reporting'],
    UpdateDoesNotChangeClass: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Parasolid: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Layer: ['Design Review'],
    Lights: ['Design Review'],
    LineType: ['Design Review'],
    Text: ['Design Review'],
    ViewPort: ['Design Review'],
    CircularReferenceFileBreak: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ECDbIssue: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    GeometricModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    ImportFailure: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    CantCreateModel: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    Error: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    MissingGCS: ['Design Review', 'Reporting', 'Clash', 'Construction'],
    IllegalUnits: ['Design Review', 'Reporting'],
    RootModelMustBePhysical: ['Design Review'],
    LinkProcessingError: ['Design Review'],
  },
};
